name: Bump tag version
on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: patch (1.0.0 -> 1.0.1), minor (1.0.0 -> 1.1.0), major (1.0.0 -> 2.0.0)
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
permissions: write-all
jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
      - name: Bump tag version
        run: |
          sh scripts/bump.sh ${{ github.event.inputs.bump_level }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
